### PR TITLE
Removed youtube popup and autoplay video

### PR DESCRIPTION
**Pull request by HiddenUserHere**

### CODE REVIEW

**Comment by pangeasi** [comment]
so... Is this script detectable by y0utube?

**Comment by HiddenUserHere** [comment]
> so... Is this script detectable by y0utube?

No, but with this fix, I can still use adblock without showing the adblock alert modal on youtube.

**Comment by pangeasi** [comment]
look, I use uBlock and pop-ups still appear 🚨

image

**Comment by HiddenUserHere** [comment]
> look, I use uBlock and pop-ups still appear 🚨 (with your fix)
> 
> image

Well, I've added few configs for buttons tooltip name that you need to change (This will be different for every language, you can get it by hovering your mouse on Play Button, this will appear like "Play (k)" then you need to change to "Play", same for Pause...)
image
image

Btw, try to disable ublock and keep using only this script on youtube.

It's working here

**Comment by kopach** [comment]
if you keep skipping this popup, after some time YouTube would block you access completely and only way to get access would be via paid subscription. So, it's not possible to use adBlock and just keep ignoring popup for very long

**Comment by pangeasi** [comment]
> if you keep skipping this popup, after some time YouTube would block you access completely and only way to get access would be via paid subscription. So, it's not possible to use adBlock and just keep ignoring popup for very long
> 
> At some point, you'll get 3 final warnings image If ignored - youtube will be blocked

ohh, it's good to know

**Pull request closed without merging**
